<link rel="stylesheet" type="text/css" href="/css/style.css">


<!-- navbar -->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container">
		<a class="navbar-brand" href="#">
			<img src="img/logo.png" class="img-fluid" style="width: 35px" alt="">
			<span style="font-weight: 10">ToDo</span>
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav">
				<li class="nav-item active">
					<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Todo List</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Done</a>
				</li>
			</ul>
		</div>

		<div class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" style="color: rgba(0,0,0,.5)" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<i class="fas fa-user"></i> Miguel
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
			<a class="dropdown-item" href="#"><i class="fas fa-address-card"></i> Profile</a>
			<a class="dropdown-item" href="#"><i class="fas fa-cog"></i> Settings</a>
			<a class="dropdown-item" href="#"><i class="fas fa-sign-out-alt"></i> Logout</a>
			</div>
		</div>
	</div>
</nav>

<!-- end navbar -->


<section>

	<div class="container mt-5">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-body">
						<button class="btn btn-primary">Add Task</button>
						<button class="btn btn-outline-secondary">Add Section</button>
						<hr>

						<div class="tasks">
							<h3>New Tasks</h3>
							<div class="row">
								<div class="col-md-4">
									<div class="group">
										<input type="checkbox" id="xd" />
										<label for="xd">Adobe XD</label>
									</div>
								</div>
								<div class="col-md-3 text-center pt-3">
									<span class="badge badge-pill badge-primary p-2">Website</span>
								</div>
								<div class="col-md-3 text-center pt-3">
									<span>Mar 24</span>
								</div>
								<div class="col-md-2 text-center pt-3">
									<button class="btn btn-outline-danger"><i class="fas fa-trash"></i></button>
									<button class="btn btn-outline-success ml-2"><i class="fas fa-pen"></i></button>
								</div>

							</div>

						</div>

					</div>
				</div>
			</div>
		</div>
	</div>

</section>




