<link rel="stylesheet" type="text/css" href="/css/style.css">


<!-- navbar -->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container">
		<a class="navbar-brand pr-4" href="#">
			<img src="img/logo.png" class="img-fluid" style="width: 35px" alt="logo">
			<span style="font-weight: 10">ToDo</span>
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link active" href="#"><i class="fas fa-list-alt"></i> Todo List</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#"><i class="fas fa-archive"></i> Archive</a>
				</li>
			</ul>
		</div>

		<div class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" style="color: rgba(0,0,0,.5)" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<i class="fas fa-user"></i> Miguel
			</a>
			<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
			<a class="dropdown-item" href="#"><i class="fas fa-address-card"></i> Profile</a>
			<a class="dropdown-item" href="#"><i class="fas fa-cog"></i> Settings</a>
			<a class="dropdown-item" href="#"><i class="fas fa-sign-out-alt"></i> Logout</a>
			</div>
		</div>
	</div>
</nav>

<!-- end navbar -->


<section>

	<div class="container mt-5">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-body">
						<button class="btn btn-primary" data-toggle="modal" data-target="#add_task">Add Task</button>
						<button class="btn btn-outline-secondary">Add Section</button>
						<hr>

						<div class="tasks">
							<h3>Study</h3>
							<div class="row">
								<div class="col-md-4">
									<div class="group">
										<input type="checkbox" id="xd" />
										<label for="xd">Matemática Discreta</label>
									</div>
								</div>
								<div class="col-md-3 text-center pt-3">
									<span class="badge badge-pill badge-primary p-2">Estudo</span>
								</div>
								<div class="col-md-3 text-center pt-3">
									<span>July 17</span>
								</div>
								<div class="col-md-2 text-center pt-3">
									<button class="btn btn-outline-danger"><i class="fas fa-trash"></i></button>
									<button class="btn btn-outline-success ml-2"><i class="fas fa-pen"></i></button>
								</div>

								<div class="col-md-4">
									<div class="group">
										<input type="checkbox" id="xd" />
										<label for="xd">Física</label>
									</div>
								</div>
								<div class="col-md-3 text-center pt-3">
									<span class="badge badge-pill badge-primary p-2">Estudo</span>
								</div>
								<div class="col-md-3 text-center pt-3">
									<span>July 17</span>
								</div>
								<div class="col-md-2 text-center pt-3">
									<button class="btn btn-outline-danger"><i class="fas fa-trash"></i></button>
									<button class="btn btn-outline-success ml-2"><i class="fas fa-pen"></i></button>
								</div>

								<div class="col-md-4">
									<div class="group">
										<input type="checkbox" id="xd" />
										<label for="xd">POO</label>
									</div>
								</div>
								<div class="col-md-3 text-center pt-3">
									<span class="badge badge-pill badge-primary p-2">Estudo</span>
								</div>
								<div class="col-md-3 text-center pt-3">
									<span>July 17</span>
								</div>
								<div class="col-md-2 text-center pt-3">
									<button class="btn btn-outline-danger"><i class="fas fa-trash"></i></button>
									<button class="btn btn-outline-success ml-2"><i class="fas fa-pen"></i></button>
								</div>

								<div class="col-md-4">
									<div class="group">
										<input type="checkbox" id="xd" />
										<label for="xd">Comprar cereais</label>
									</div>
								</div>
								<div class="col-md-3 text-center pt-3">
									<span class="badge badge-pill badge-success p-2">Compras</span>
								</div>
								<div class="col-md-3 text-center pt-3">
									<span>July 17</span>
								</div>
								<div class="col-md-2 text-center pt-3">
									<button class="btn btn-outline-danger"><i class="fas fa-trash"></i></button>
									<button class="btn btn-outline-success ml-2"><i class="fas fa-pen"></i></button>
								</div>

							</div>

						</div>

					</div>
				</div>
			</div>
		</div>
	</div>

</section>


<!-- modal -->

<div class="modal fade" id="add_task">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header bg-primary text-white">
				<h3 class="modal-title" style="font-weight: 100;">Add new Task</h3>
				<i class="fas fa-tasks" style="font-size: 40px;"></i>
			</div>
			<div class="modal-body">
				<form method="post" action="">
					<div class="form-group">
						<label for="name-task" class="form-conrol-label">Task Name</label>
						<input type="text" class="form-control" style="box-shadow: none;" name="name" id="name-task" required>
					</div>

					<div class="form-group">
						<label for="category-task" class="form-conrol-label">Task Date</label>
						<select style="box-shadow: none;" name="category" id="category-task" class="form-control">
							<option>gkgkdg</option>
							<option>gkgkd</option>
						</select>
					</div>

					<div class="form-group mb-4">
						<label for="section-task" class="form-conrol-label">Task Section</label>
						<select style="box-shadow: none;" name="section" id="section-task" class="form-control">
							<option>gkgkdg</option>
							<option>gkgkd</option>
						</select>
					</div>

					<div class="modal-footer">
						<button class="btn btn-outline-danger" data-dismiss="modal">Cancel</button>
						<button class="btn btn-outline-success" type="submit">Add</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<!-- end modal -->




