<link rel="stylesheet" type="text/css" href="/css/style.css">
<!-- header -->
		
		<header>
			<div class="container">
				<div class="row">
					<div class="col-md-2"></div>
					<div class="col-md-6">
						<div class="logo">
							<img class="img-fluid" src="img/logo.png" alt="RedeHypex">
						</div>
					</div>
					<div class="col-md-4">
						<div class="online">
							<h3>
								Aventure-se com os
								<span><?= $this->view->onlineplayers ?></span>
								<br>
								<b>jogadores</b>
								online
							</h3>
							<button id="copy" data-clipboard-text="jogar.redehypex.com" class="btn btn-yellow">
								<i class="fas fa-gamepad"></i> JOGUE AGORA
							</button>
						</div>
					</div>
				</div>
			</div>
		</header>

		<!-- end header -->

		<!-- navbar -->

		<section>
			<div class="container">
				<nav class="navbar menu navbar-expand-lg">
					<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav">☰</button>
					<div id="navbarNav" class="collapse navbar-collapse">
						<ul class="navbar-nav">
							<li class="nav-item active" style="border-radius: 4px 0 0 0;"><a href="#" class="nav-link">Início</a></li>
							<li class="nav-item"><a href="/loja" class="nav-link">Loja</a></li>
							<li class="nav-item"><a href="/punicoes" class="nav-link">Punições</a></li>
							<li class="nav-item"><a href="/equipe" class="nav-link">Equipe</a></li>
							<li class="nav-item"><a href="/regras" class="nav-link">Regras</a></li>
							<li class="nav-item"><a href="/aplicar" class="nav-link">Aplica-se</a></li>
						</ul>
						<ul class="navbar-nav ml-auto">

							<li class="nav-item active" style="border-radius: 0 4px 0 0;"><a href="/carrinho" class="nav-link"><i class="fas fa-shopping-cart"></i> <?= $this->view->carrinhoQuantidade ?></a></li>
						</ul>
					</div>
				</nav>
			</div>
		</section>

		<!-- end navbar -->


		<!-- content -->

		<section class="container">
			<div class="content mb-5">
				<div class="row">
					<div class="col-md-9">

						<?php foreach ($this->view->allnoticias as $key => $noticia) { ?>
							
							<div class="card">
								<div class="header">
									<div class="avatar">
										<img class="img-fluid rounded" src="https://minotar.net/helm/<?= $noticia['autor'] ?>/76.png">
									</div>
									<div>
										<span>
											Postado por <?= $noticia['autor'] ?>
											<br>
											<b><?= $this->dataNoticia($noticia['dateTime']); ?></b>
										</span>
									</div>
								</div>
								<div class="card-title">
									<h3><?= $noticia['titulo'] ?></h3>
								</div>
								<div class="card-body textoNoticia">
									<?= $this->lessTexto($noticia['texto']); ?>
								</div>
								<?php if($this->textoReadMore($noticia['texto']) == true) { ?>
	                                <div class="text-center pb-3">
										<a href="/noticia?id=<?=$noticia['id']?>" class="btn btn-yellow" style="font-weight: 400;">CONTINUAR LENDO</a>
									</div>
	                            <?php } ?>
							</div>

						<?php } ?>

						<!-- Pagination -->

						<nav>
							<ul class="pagination justify-content-center mt-5">
								<li class="page-item disabled mr-2"><a class="page-link" href="#">Início</a></li>
								<li class="page-item active"><a class="page-link" href="#">1</a></li>
								<li class="page-item disabled ml-2"><a class="page-link" href="#">Último</a></li>
							</ul>
						</nav>

						<!-- end Pagination -->

					</div>
					<div class="col-md-3">
						<div class="card">
							<div class="card-title">
								<i class="fas fa-archive"></i> Mais vendido
							</div>
							<div class="card-body p-3">
								<div class="package">
									<img class="img-fluid" src="img/vip1.png">
									<div class="title">VIP - 30 Dias</div>
									<div class="price">R$39,90</div>
									<button class="btn btn-block btn-success text-uppercase">Comprar</button>
								</div>
							</div>
						</div>
						<div class="card">
							<iframe src="https://discordapp.com/widget?id=640244110275379205&theme=dark" height="500" allowtransparency="true" frameborder="0"></iframe>
						</div>
					</div>
				</div>
			</div>
		</section>
		
		<!-- end content -->


		<!-- footer -->

		<footer>
			<div class="container">
				<div class="row">
					<div class="col-md-6">
						© RedeHypex - Não temos nenhuma afiliação com a Mojang AB
						<span class="player-count"></span>
					</div>
					<div class="col-md-6">
						<div class="social-icons">
							<span>
								<a class="btn-discord btn-social" href="#" target="_blank"><i class="fab fa-discord"></i></a>
							</span>
							<span>
								<a class="btn-twitter btn-social mx-2" href="#" target="_blank"><i class="fab fa-twitter"></i></a>
							</span>
							<span>
								<a class="btn-youtube btn-social" href="#" target="_blank"><i class="fab fa-youtube"></i></a>
							</span>
						</div>
					</div>
				</div>
			</div>
		</footer>

		<!-- end footer -->