<link rel="stylesheet" type="text/css" href="/css/style.css">



<section>

	<div class="container mt-5">
		<div class="row">
			<div class="col-md-12">
				<div class="card" style="border-top: 7px solid #007bff">
					<div class="card-body">
                        <div class="row">

                            <div class="col-md-5 p-5">
                                <center>
                                    <img src="img/logo.png" alt="logo" class="img-fluid">
                                    <h3>ToDo APP</h3>
                                    <span>Whether for work or leisure, To Do makes your life easier.</span>
                                </center>
                            </div>

                            <div class="col-md-2"></div>

                            <div class="col-md-5">
                                <div class="card-body">
                                    <h3 style="font-weight: bold;">SIGN IN</h3>
                                    <form method="post" action="/login">
                                        <label class="mt-3">User</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">
                                                    <i class="fas fa-user"></i>
                                                </span>
                                            </div>
                                            <input name="user" style="box-shadow: none;" class="form-control" type="text" required>
                                        </div>
                                        <label class="mt-3">Password</label>
                                        <div class="input-group mb-4">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">
                                                    <i class="fas fa-lock"></i>
                                                </span>
                                            </div>
                                            <input name="senha" style="box-shadow: none;" class="form-control" type="password" required>
                                        </div>
                                        <button class="btn btn-primary btn-block" type="submit" style="text-transform: uppercase; font-weight: 400;">Sign In</button>
                                        
                                    </form>
                                </div>
                            </div>

                        </div>

					</div>
				</div>
			</div>
		</div>
	</div>

</section>


