<link rel="stylesheet" type="text/css" href="/css/style.css">
<!-- header -->
		
		<header>
			<div class="container">
				<div class="row">
					<div class="col-md-2"></div>
					<div class="col-md-6">
						<div class="logo">
							<img class="img-fluid" src="img/logo.png" alt="RedeHypex">
						</div>
					</div>
					<div class="col-md-4">
						<div class="online">
							<h3>
								Aventure-se com os
								<span><?= $this->view->onlineplayers ?></span>
								<br>
								<b>jogadores</b>
								online
							</h3>
							<button id="copy" data-clipboard-text="jogar.redehypex.com" class="btn btn-yellow">
								<i class="fas fa-gamepad"></i> JOGUE AGORA
							</button>
						</div>
					</div>
				</div>
			</div>
		</header>

		<!-- end header -->

		<!-- navbar -->

		<section>
			<div class="container">
				<nav class="navbar menu navbar-expand-lg">
					<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav">☰</button>
					<div id="navbarNav" class="collapse navbar-collapse">
						<ul class="navbar-nav">
							<li class="nav-item" style="border-radius: 4px 0 0 0;"><a href="/" class="nav-link">Início</a></li>
							<li class="nav-item active"><a href="#" class="nav-link">Loja</a></li>
							<li class="nav-item"><a href="/punicoes" class="nav-link">Punições</a></li>
							<li class="nav-item"><a href="/equipe" class="nav-link">Equipe</a></li>
							<li class="nav-item"><a href="/regras" class="nav-link">Regras</a></li>
							<li class="nav-item"><a href="/aplicar" class="nav-link">Aplica-se</a></li>
						</ul>
						<ul class="navbar-nav ml-auto">

							<li class="nav-item active" style="border-radius: 0 4px 0 0;"><a href="/carrinho" class="nav-link"><i class="fas fa-shopping-cart"></i> <?= $this->view->carrinhoQuantidade ?></a></li>
						</ul>
					</div>
				</nav>
			</div>
		</section>

		<!-- end navbar -->


		<!-- content -->

		<section class="container">
			<div class="content mb-5">
				<div class="row">
					<div class="col-md-3">
						<div class="card">
							<div class="card-body">
								<h5>Selecione:</h5>
								<hr>
								<ul class="menu-horizontal">
									<?php foreach ($this->view->allcategorias as $key => $categoria) { ?>
										<li>
											
											<?php if((isset($_GET['c']) != 1 || $_GET['c'] == '') || ($categoria['id'] != $_GET['c'])) { ?>

												<a class="d-flex justify-content-between" href="/loja?c=<?= $categoria['id'] ?>"><?= $categoria['nome'] ?>
													<span class="d-flex align-items-center justify-content-center badge badge-yellow"><?= $this->getSize($categoria['id']) ?></span>
												</a>

											<?php } ?>

											<?php if((isset($_GET['c']) == 1) && ($_GET['c'] == $categoria['id'])) { ?>

												<a style="color: #FFBC04;" class="d-flex justify-content-between" href="/loja?c=<?= $categoria['id'] ?>"><?= $categoria['nome'] ?>
													<span class="d-flex align-items-center justify-content-center badge badge-yellow"><?= $this->getSize($categoria['id']) ?></span>
												</a>

											<?php } ?>


										</li>
									<?php } ?>
								</ul>
							</div>
						</div>
						<div class="card">
							<div class="card-body">
								<h5>Meta mensal:</h5>
								<div class="progress mt-3">
      								<div class="progress-bar progress-yellow" style="width: 75%;">75%</div>
    							</div>
							</div>
						</div>
					</div>

					<?php if(isset($_GET['c']) != 1 || $_GET['c'] == '') { ?>
						<div class="col-md-9">
							<div class="card card-loja">
								<div class="card-body">
									<h5 class="m-0 text-uppercase" style="font-weight: 600;">A Loja Oficial</h5>
									<b>RedeHypex</b>
									<p class="mt-3">
										Bem-vindo à nossa loja. Todas as compras contribuem para o desenvolvimento e
										manutenção dos servidores.
										Certifique-se de inserir nick usado no servidor! Com letras maiúsculas e minúsculas.
										Sua compra é ativada assim que o pagamento for aprovado! 
									</p>
								</div>
							</div>
							<div class="card card-aviso">
								<div class="card-body">
									<i class="fas fa-exclamation-triangle"></i> Antes de efetuar uma compra, LEIA os TERMOS de USO: Replamações posteiores não serão aceites.
								</div>
							</div>
						</div>
					<?php } ?>

					<div class="col-md-9">
						<div class="row">

							<?php if(isset($_GET['c']) == 1 && $_GET['c'] != '') { ?>

								<?php foreach ($this->view->pacotesCategoria as $key => $pacote) { ?>

									<div class="col-md-4">
										<div class="card">
											<div class="card-body">
												<center>
													<img class="img-fluid" src="<?=$pacote['img_url']?>">
												</center>
												<div class="text-left mt-4" style="font-weight: 400; font-size: 18px;"><?=$pacote['nome']?></div>
												<div class="text-left" style="color: #3FC75F; font-weight: 600; font-size: 18px;">R$<?=$pacote['preco']?></div>
												<div class="row mt-3">
													<div class="col-md-9">
														<a href="/add?id=<?=$pacote['id']?>&c=<?=$_GET['c']?>" class="btn btn-success btn-block text-uppercase text-white"><i class="fas fa-shopping-cart"></i> adicionar</a>
													</div>
													<div class="col-md-3 pl-0">
														<a href="/detalhes?p=<?=$pacote['id']?>" class="btn btn-dark btn-block" style="height: 100%;">
															<i class="fas fa-exclamation-circle text-white pt-1"></i>
														</a>
													</div>
												</div>
											</div>
										</div>
									</div>

								<?php } ?>

								<?php if(count($this->view->pacotesCategoria) <= 0) { ?>

									<div class="col-md-12">
										<h5 class="text-center text-muted mt-3" style="font-weight: 600;">Não há produtos</h5>
									</div>

								<?php } ?>

							<?php } ?>

						</div>
					</div>
	
				</div>
			</div>
		</section>
		
		<!-- end content -->


		<!-- footer -->

		<footer>
			<div class="container">
				<div class="row">
					<div class="col-md-6">
						© RedeHypex - Não temos nenhuma afiliação com a Mojang AB
					</div>
					<div class="col-md-6">
						<div class="social-icons">
							<span>
								<a class="btn-discord btn-social" href="#" target="_blank"><i class="fab fa-discord"></i></a>
							</span>
							<span>
								<a class="btn-twitter btn-social mx-2" href="#" target="_blank"><i class="fab fa-twitter"></i></a>
							</span>
							<span>
								<a class="btn-youtube btn-social" href="#" target="_blank"><i class="fab fa-youtube"></i></a>
							</span>
						</div>
					</div>
				</div>
			</div>
		</footer>
		<!-- end footer -->